  version: '3.1'
  services:
    # apache:
    #   image: 'php:latest'
    #   container_name: php
    #   restart: always
    #   ports:
    #     - '80:80'
    #   volumes:
    #     - ./html:/var/www/html
    #   depends_on:
    #     - mysqldb
    #   links:
    #     - db       
    db:
      image: mysql:latest
      container_name: sit
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=sit